#
# Locks the door when closed for a variable amount of time or unlocks when open to allow the door to close properly

blueprint:
  name: Automated lock control
  description: Locks the door when closed for a variable amount of time or unlocks when open to allow the door to close properly
  domain: automation
  input:
    door:
      name: Door
      selector:
        entity:
          domain: binary_sensor
          
    lock:
      name: Lock
      selector:
        entity:
          domain: lock

    ttl:
      name: Time-to-lock
      default: 10
      selector:
        number:
          min: 0
          max: 300
          step: 1
          unit_of_measurement: 'seconds'
          mode: slider
    
    ttu:
      name: Time-to-unlock
      default: 120
      selector:
        number:
          min: 0
          max: 300
          step: 1
          unit_of_measurement: 'seconds'
          mode: slider

mode: single

trigger:
  - platform: state
    entity_id: !input lock
    to: 'locked'
    for:
      seconds: !input ttu
  - platform: state
    entity_id: !input door
    to: 'off'
    for:
      seconds: !input ttl
  - platform: state
    entity_id: !input lock
    to: 'unlocked'
    for:
      seconds: !input ttl

action:
  - choose:
    - alias: 'Unlock when door locked and open to prevent getting stuck after ttu'
      conditions:
        - condition: state
          entity_id: !input door
          state: 'on'
        - condition: state
          entity_id: !input lock
          state: 'locked'
      sequence:
        - service: lock.unlock
          entity_id: !input lock
    - alias: 'Automatically lock on door closed for ttl'
      conditions:
        - condition: state
          entity_id: !input door
          state: 'off'
        - condition: state
          entity_id: !input lock
          state: 'unlocked'
      sequence:
        - service: lock.lock
          entity_id: !input lock