#
# Locks the door when closed for a variable amount of time or unlocks when open to allow the door to close properly

blueprint:
  name: Automated lock control
  description: Locks the door when closed for a variable amount of time or unlocks when open to allow the door to close properly
  domain: automation
  input:
    door:
      name: Door
      selector:
        entity:
          domain: binary_sensor
          
    lock:
      name: Lock
      selector:
        entity:
          domain: lock

    ttl:
      name: Time-to-lock
      default: 10
      selector:
        number:
          min: 0
          max: 300
          step: 1
          unit_of_measurement: 'seconds'
          mode: slider

mode: restart

variables:
  door: !input door
  lock: !input lock
  ttl: !input ttl

trigger:
  - platform: state
    entity_id: !input door

condition:
  - condition: template
    value_template: '{{ is_state(trigger.entity_id, 'on') or (trigger.for >= ttl) }}'
  - condition: template
    value_template: '{{ (is_state(trigger.entity_id, 'on') and is_state(lock, 'locked')) or (is_state(trigger.entity_id, 'off') and is_state(lock, 'unlocked')) }}'

action:
  - service_template: lock.{{ 'lock' if is_state(trigger.entity_id, 'off') else 'unlock' }}
    entity_id: !input lock

