#
# Locks the door when closed for a variable amount of time

blueprint:
  name: Lock after closing
  description: Locks the door when closed for a variable amount of time
  domain: automation
  input:
    door:
      name: Door
      selector:
        entity:
          domain: binary_sensor
          
    lock:
      name: Lock
      selector:
        entity:
          domain: lock

    ttl:
      name: Time-to-lock
      default: 10
      selector:
        number:
          min: 0
          max: 300
          step: 1
          unit_of_measurement: 'seconds'
          mode: slider

mode: restart

trigger:
  - platform: state
    entity_id: !input door
    for:
      seconds: !input ttl

condition:
  - condition: state
    entity_id: !input door
    state: 'off'

action:
  - service: lock.lock
    entity_id: !input lock
