#
# Dims lights when media is played and reverts back to previous brightness when stopped/paused

blueprint:
  name: Theatre-style Dimming
  description: Dims lights when media is played and reverts back to previous brightness when stopped/paused
  domain: automation
  input:
    room_light:
      name: Light
      selector:
        entity:
          domain: light
          
    media_player:
      name: Media Player
      selector:
        entity:
          domain: media_player

    dimmed_brightness:
      name: Dimmed Brightness
      default: 10
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: '%'
          mode: slider

    ttd:
      name: Time-to-dim
      default: 10
      selector:
        number:
          min: 0
          max: 30
          step: 1
          unit_of_measurement: 'seconds'
          mode: slider

    dim_duration:
      name: Dim Duration
      default: 3
      selector:
        number:
          min: 0
          max: 30
          step: 1
          unit_of_measurement: 'seconds'
          mode: slider

mode: single

variables:
  room_light: !input room_light
  scene_id: persistence_{{ room_light.split('.')[1] }}

trigger:
  - platform: state
    entity_id: !input media_player
    to: playing

condition:
  - condition: numeric_state
    entity_id: !input room_light
    value_template: >
      {% (if states.{{ room_light }}).state == 'on' %}
        {{ (states.{{ room_light }}).attributes.brightness }}
      {% else %} 0 {% endif %}
    above: !input dimmed_brightness

action:
  - service: scene.create
    data_template:
      scene_id: {{ scene_id }}
      snapshot_entities: !input room_light
  - service: light.turn_on
    data:
      brightness_pct: !input dimmed_brightness
      transition: !input dim_duration
    target:
      entity_id: !input room_light
  - wait_for_trigger:
    - platform: state
      entity_id: !input media_player
      for:
        hours: 0
        minutes: 0
        seconds: !input ttd
  - service: scene.turn_on
    data_template:
      entity_id: scene.{{ scene_id }}
      transition: !input dim_duration
