#
# Dims lights when media is played and reverts back to previous brightness when stopped/paused

blueprint:
  name: Theatre-style Dimming
  description: Dims lights when media is played and reverts back to previous brightness when stopped/paused
  domain: automation
  input:
    room_light:
      name: Light
      selector:
        entity:
          domain: light
          
    media_player:
      name: Media Player
      selector:
        entity:
          domain: media_player

    dimmed_brightness:
      name: Dimmed Brightness
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: '%'
          mode: slider

    scene_id:
      name: Scene ID

mode: single

variables:
  scene_id: !input scene_id

trigger:
  - platform: state
    entity_id: !input media_player
    for:
      hours: 0
      minutes: 0
      seconds: 5

condition:
  - condition: state
    entity_id: !input room_light
    state: 'on'

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input media_player
            state: playing
            for:
              hours: 0
              minutes: 0
              seconds: 0
        sequence:
          - service: scene.create
            data:
              scene_id: !input scene_id
              snapshot_entities: !input room_light
          - service: light.turn_on
            data:
              brightness_pct: !input dimmed_brightness
              transition: 3
            target:
              entity_id: !input room_light
    default:
      - service: scene.turn_on
        data_template:
          entity_id: 'scene.{{ scene_id }}'
          transition: 3
